---
title: "FinalProject_2.0"
author: "Group 2"
date: "April 8, 2017"
output: word_document
---

```{r setup, include=FALSE}
processed_fake <- read.csv("/Users/setaresarachi/Desktop/INFSCI 2160/DataMiningFinalProject/preprocessed_fake.csv")
processed_fake <- read.csv("preprocessed_fake.csv")
#Removing uuid and default 'x' column
processed_fake<- processed_fake[,c(-1,-3)]
```

```{r PreProcessing}
#changing factors to characters

processed_fake$author <- as.character(processed_fake$author)
processed_fake$title <- as.character(processed_fake$title)
processed_fake$crawled <- as.character(processed_fake$crawled)
processed_fake$site_url <- as.character(processed_fake$site_url)

#setting domain ranks with NAs to 0
processed_fake$domain_rank[which(is.na(processed_fake$domain_rank))] <- 0

#taking required columns
df_data <- processed_fake[,c(1,2,5,6,7,8,9,10,11,12,13,14,15)]
#df_data <- df_data[,c(-1,-2)]

#converting integer to numeric
df_data$domain_rank <- as.numeric(df_data$domain_rank)
df_data$replies_count <- as.numeric((df_data$replies_count))
df_data$participants_count <- as.numeric((df_data$participants_count))
df_data$comments <- as.numeric((df_data$comments))
df_data$likes<- as.numeric((df_data$likes))
df_data$shares <- as.numeric((df_data$shares))
  
#Changing rumor to bs
df_data$type[which(df_data$type %in% c('state','fake','rumor'))] <- 'fake'
#removing the level rumor
df_data$type <- as.factor(as.character(df_data$type))
table(df_data$type)
```

```{r Summary_and_Statistical_Analysis}
domain_rank.sum <- c(summary(processed_fake$domain_rank), sd(processed_fake$domain_rank))
spam_score.sum<-c(summary(processed_fake$spam_score), sd(processed_fake$spam_score))
replies_count.sum<-c(summary(processed_fake$replies_count), sd(processed_fake$replies_count))
participants_count.sum<-c(summary(processed_fake$participants_count), sd(processed_fake$participants_count))
likes.sum<-c(summary(processed_fake$likes), sd(processed_fake$likes))
comments.sum<-c(summary(processed_fake$comments), sd(processed_fake$comments))
shares.sum<-c(summary(processed_fake$shares), sd(processed_fake$shares))

result = cbind(domain_rank.sum, spam_score.sum, replies_count.sum, participants_count.sum, likes.sum, comments.sum, shares.sum)

result = as.data.frame(result)
rownames(result)[7] <- c("sd")
colnames(result) <- c("Domain Rank","Spam Score","Replies Count","Participants Count", "Likes","Comments","Shares")
library(knitr)
kable(result, caption = 'Table 1: Summary of attributes')

```

```{r plot_of_frequency_of_categorical_vars}
library(ggplot2)
#Plot of frequency of "type"
ggplot(processed_fake , aes(x = processed_fake$type, fill = processed_fake$type))+ 

  geom_bar(alpha = 0.8) +
  ggtitle("Histogram Plot:  Type") + 

  labs(x = "Type", y = "Counts") + 
  guides(fill=guide_legend(title="Type")) +
  theme(plot.title = element_text(hjust = 0.5))

#Plot of frequency of "countries"
ggplot(processed_fake , aes(x = processed_fake$country, fill = processed_fake$country))+ 

  geom_bar(alpha = 0.63) +
  ggtitle("Histogram Plot:  Country") + 
  labs(x = "Country", y = "Counts") + 
  guides(fill=guide_legend(title="Country")) +
  theme(plot.title = element_text(hjust = 0.5))

#Plot of distribution of types for each country
ggplot(processed_fake , aes(x = processed_fake$country, fill = processed_fake$type))+ 
  geom_bar(alpha = 0.63) +
  ggtitle("Histogram Plot:  Distribution of Type for each Country") + 
  labs(x = "Country", y = "Type Distribution") + 
  guides(fill=guide_legend(title="Type")) +
  theme(plot.title = element_text(hjust = 0.5))

#Number of Participants for each Type
participants.count_type <- aggregate(participants_count~type,processed_fake,sum)
ggplot(participants.count_type , aes(x = type, y = participants_count, fill= participants_count))+ 
  geom_bar(alpha = 0.7,stat = "Identity") +
  ggtitle("Histogram Plot: Number of Participants for each Type") + 
  labs(x = "Type", y = "Counts") + 
  guides(fill=guide_legend(title=" Count")) +
  theme(plot.title = element_text(hjust = 0.5))+
  scale_fill_continuous(low="red",high="yellow", limits=c(0,9000))
```
  
```{r MultinomReg}  
library(nnet)
model_logit<-multinom(formula= type ~.,data = df_data)
```

```{r RandomForest}
library(randomForest)
rf_model <- randomForest(formula = type ~., data = df_data,ntree=100)
importance(rf_model)
str(df_data)
```

```{r kFoldRandomForest}
library(randomForest)
library(MASS) 
library(tree)
library(party)
decisionTree_matr <- as.matrix(df_data)
```

```{r 1Vs1_bait_satire}
table(df_data$type)
bait_satire <- df_data[which(df_data$type %in% c("bait", "satire")),]
bait_satire$type <- as.character(bait_satire$type)
table(bait_satire$type)
bait_satire$type[which(bait_satire$type %in% "bait")] <- 0
bait_satire$type[which(bait_satire$type %in% "satire")] <- 1
bait_satire$type <- as.factor(bait_satire$type)
```

```{r 1Vs1_bait_bias}
table(df_data$type)
bait_bias <- df_data[which(df_data$type %in% c("bait", "bias")),]
bait_bias$type <- as.character(bait_bias$type)
table(bait_bias$type)
bait_bias$type[which(bait_bias$type %in% "bait")] <- 0
bait_bias$type[which(bait_bias$type %in% "bias")] <- 1
bait_bias$type <- as.factor(bait_bias$type)
```

```{r 1Vs1_bait_bs}
table(df_data$type)
bait_bs <- df_data[which(df_data$type %in% c("bait", "bs")),]
bait_bs$type <- as.character(bait_bs$type)
table(bait_bs$type)
bait_bs$type[which(bait_bs$type %in% "bait")] <- 0
bait_bs$type[which(bait_bs$type %in% "bs")] <- 1
bait_bs$type <- as.factor(bait_bs$type)
```

```{r 1Vs1_bait_conspiracy}
table(df_data$type)
bait_conspiracy <- df_data[which(df_data$type %in% c("bait", "conspiracy")),]
bait_conspiracy$type <- as.character(bait_conspiracy$type)
table(bait_conspiracy$type)
bait_conspiracy$type[which(bait_conspiracy$type %in% "bait")] <- 0
bait_conspiracy$type[which(bait_conspiracy$type %in% "conspiracy")] <- 1
bait_conspiracy$type <- as.factor(bait_conspiracy$type)
```

```{r 1Vs1_bait_fake}
table(df_data$type)
bait_fake <- df_data[which(df_data$type %in% c("bait", "fake")),]
bait_fake$type <- as.character(bait_fake$type)
table(bait_fake$type)
bait_fake$type[which(bait_fake$type %in% "bait")] <- 0
bait_fake$type[which(bait_fake$type %in% "fake")] <- 1
bait_fake$type <- as.factor(bait_fake$type)
```

```{r 1Vs1_bait_hate}
table(df_data$type)
bait_hate <- df_data[which(df_data$type %in% c("bait", "hate")),]
bait_hate$type <- as.character(bait_hate$type)
table(bait_hate$type)
bait_hate$type[which(bait_hate$type %in% "bait")] <- 0
bait_hate$type[which(bait_hate$type %in% "hate")] <- 1
bait_hate$type <- as.factor(bait_hate$type)
```

```{r 1Vs1_bait_junksci}
table(df_data$type)
bait_junksci <- df_data[which(df_data$type %in% c("bait", "junksci")),]
bait_junksci$type <- as.character(bait_junksci$type)
table(bait_junksci$type)
bait_junksci$type[which(bait_junksci$type %in% "bait")] <- 0
bait_junksci$type[which(bait_junksci$type %in% "junksci")] <- 1
bait_junksci$type <- as.factor(bait_junksci$type)
```

```{r 1Vs1_bias_bs}
table(df_data$type)
bias_bs <- df_data[which(df_data$type %in% c("bias", "bs")),]
bias_bs$type <- as.character(bias_bs$type)
table(bias_bs$type)
bias_bs$type[which(bias_bs$type %in% "bias")] <- 0
bias_bs$type[which(bias_bs$type %in% "bs")] <- 1
bias_bs$type <- as.factor(bias_bs$type)
```

```{r 1Vs1_bias_conspiracy}
table(df_data$type)
bias_conspiracy <- df_data[which(df_data$type %in% c("bias", "conspiracy")),]
bias_conspiracy$type <- as.character(bias_conspiracy$type)
table(bias_conspiracy$type)
bias_conspiracy$type[which(bias_conspiracy$type %in% "bias")] <- 0
bias_conspiracy$type[which(bias_conspiracy$type %in% "conspiracy")] <- 1
bias_conspiracy$type <- as.factor(bias_conspiracy$type)
```

```{r 1Vs1_bias_fake}
table(df_data$type)
bias_fake <- df_data[which(df_data$type %in% c("bias", "fake")),]
bias_fake$type <- as.character(bias_fake$type)
table(bias_fake$type)
bias_fake$type[which(bias_fake$type %in% "bias")] <- 0
bias_fake$type[which(bias_fake$type %in% "fake")] <- 1
bias_fake$type <- as.factor(bias_fake$type)
```

```{r 1Vs1_bias_hate}
table(df_data$type)
bias_hate <- df_data[which(df_data$type %in% c("bias", "hate")),]
bias_hate$type <- as.character(bias_hate$type)
table(bias_hate$type)
bias_hate$type[which(bias_hate$type %in% "bias")] <- 0
bias_hate$type[which(bias_hate$type %in% "hate")] <- 1
bias_hate$type <- as.factor(bias_hate$type)
table(bias_hate$type)
```

```{r 1Vs1_bias_junksci}
table(df_data$type)
bias_junksci <- df_data[which(df_data$type %in% c("bias", "junksci")),]
bias_junksci$type <- as.character(bias_junksci$type)
table(bias_junksci$type)
bias_junksci$type[which(bias_junksci$type %in% "bias")] <- 0
bias_junksci$type[which(bias_junksci$type %in% "junksci")] <- 1
bias_junksci$type <- as.factor(bias_junksci$type)
table(bias_junksci$type)
```

```{r 1Vs1_bias_satire}
table(df_data$type)
bias_satire <- df_data[which(df_data$type %in% c("bias", "satire")),]
bias_satire$type <- as.character(bias_satire$type)
table(bias_satire$type)
bias_satire$type[which(bias_satire$type %in% "bias")] <- 0
bias_satire$type[which(bias_satire$type %in% "satire")] <- 1
bias_satire$type <- as.factor(bias_satire$type)
table(bias_satire$type)
```

```{r 1Vs1_bs_conspiracy}
table(df_data$type)
bs_conspiracy <- df_data[which(df_data$type %in% c("bs", "conspiracy")),]
bs_conspiracy$type <- as.character(bs_conspiracy$type)
table(bs_conspiracy$type)
bs_conspiracy$type[which(bs_conspiracy$type %in% "bs")] <- 0
bs_conspiracy$type[which(bs_conspiracy$type %in% "conspiracy")] <- 1
bs_conspiracy$type <- as.factor(bs_conspiracy$type)
table(bs_conspiracy$type)
```

```{r 1Vs1_bs_fake}
table(df_data$type)
bs_fake <- df_data[which(df_data$type %in% c("bs", "fake")),]
bs_fake$type <- as.character(bs_fake$type)
table(bs_fake$type)
bs_fake$type[which(bs_fake$type %in% "bs")] <- 0
bs_fake$type[which(bs_fake$type %in% "fake")] <- 1
bs_fake$type <- as.factor(bs_fake$type)
table(bs_fake$type)
```

```{r 1Vs1_bs_hate}
table(df_data$type)
bs_hate <- df_data[which(df_data$type %in% c("bs", "hate")),]
bs_hate$type <- as.character(bs_hate$type)
table(bs_hate$type)
bs_hate$type[which(bs_hate$type %in% "bs")] <- 0
bs_hate$type[which(bs_hate$type %in% "hate")] <- 1
bs_hate$type <- as.factor(bs_hate$type)
table(bs_hate$type)
```

```{r 1Vs1_bs_junksci}
table(df_data$type)
bs_junksci <- df_data[which(df_data$type %in% c("bs", "junksci")),]
bs_junksci$type <- as.character(bs_junksci$type)
table(bs_junksci$type)
bs_junksci$type[which(bs_junksci$type %in% "bs")] <- 0
bs_junksci$type[which(bs_junksci$type %in% "junksci")] <- 1
bs_junksci$type <- as.factor(bs_junksci$type)
table(bs_junksci$type)
```

```{r 1Vs1_bs_satire}
table(df_data$type)
bs_satire <- df_data[which(df_data$type %in% c("bs", "satire")),]
bs_satire$type <- as.character(bs_satire$type)
table(bs_satire$type)
bs_satire$type[which(bs_satire$type %in% "bs")] <- 0
bs_satire$type[which(bs_satire$type %in% "satire")] <- 1
bs_satire$type <- as.factor(bs_satire$type)
table(bs_satire$type)
```

```{r 1Vs1_conspiracy_fake}
table(df_data$type)
conspiracy_fake <- df_data[which(df_data$type %in% c("fake", "conspiracy")),]
conspiracy_fake$type <- as.character(conspiracy_fake$type)
table(conspiracy_fake$type)
conspiracy_fake$type[which(conspiracy_fake$type %in% "conspiracy")] <- 0
conspiracy_fake$type[which(conspiracy_fake$type %in% "fake")] <- 1
conspiracy_fake$type <- as.factor(conspiracy_fake$type)
table(conspiracy_fake$type)
```

```{r 1Vs1_conspiracy_hate}
table(df_data$type)
conspiracy_hate <- df_data[which(df_data$type %in% c("conspiracy", "hate")),]
conspiracy_hate$type <- as.character(conspiracy_hate$type)
table(conspiracy_hate$type)
conspiracy_hate$type[which(conspiracy_hate$type %in% "conspiracy")] <- 0
conspiracy_hate$type[which(conspiracy_hate$type %in% "hate")] <- 1
conspiracy_hate$type <- as.factor(conspiracy_hate$type)
table(conspiracy_hate$type)
```

```{r 1Vs1_conspiracy_junksci}
table(df_data$type)
conspiracy_junksci <- df_data[which(df_data$type %in% c("junksci", "conspiracy")),]
conspiracy_junksci$type <- as.character(conspiracy_junksci$type)
table(conspiracy_junksci$type)
conspiracy_junksci$type[which(conspiracy_junksci$type %in% "conspiracy")] <- 0
conspiracy_junksci$type[which(conspiracy_junksci$type %in% "junksci")] <- 1
conspiracy_junksci$type <- as.factor(conspiracy_junksci$type)
table(conspiracy_junksci$type)
```

```{r 1Vs1_conspiracy_satire}
table(df_data$type)
conspiracy_satire <- df_data[which(df_data$type %in% c("satire", "conspiracy")),]
conspiracy_satire$type <- as.character(conspiracy_satire$type)
table(conspiracy_satire$type)
conspiracy_satire$type[which(conspiracy_satire$type %in% "conspiracy")] <- 0
conspiracy_satire$type[which(conspiracy_satire$type %in% "fake")] <- 1
conspiracy_satire$type <- as.factor(conspiracy_satire$type)
table(conspiracy_satire$type)
```

```{r 1Vs1_fake_hate}
table(df_data$type)
fake_hate <- df_data[which(df_data$type %in% c("fake", "hate")),]
fake_hate$type <- as.character(fake_hate$type)
table(fake_hate$type)
fake_hate$type[which(fake_hate$type %in% "fake")] <- 0
fake_hate$type[which(fake_hate$type %in% "hate")] <- 1
fake_hate$type <- as.factor(fake_hate$type)
table(fake_hate$type)
```

```{r 1Vs1_fake_junksci}
table(df_data$type)
fake_junksci <- df_data[which(df_data$type %in% c("fake", "junksci")),]
fake_junksci$type <- as.character(fake_junksci$type)
table(fake_junksci$type)
fake_junksci$type[which(fake_junksci$type %in% "fake")] <- 0
fake_junksci$type[which(fake_junksci$type %in% "junksci")] <- 1
fake_junksci$type <- as.factor(fake_junksci$type)
table(fake_junksci$type)
```

```{r 1Vs1_fake_satire}
table(df_data$type)
fake_satire <- df_data[which(df_data$type %in% c("fake", "satire")),]
fake_satire$type <- as.character(fake_satire$type)
table(fake_satire$type)
fake_satire$type[which(fake_satire$type %in% "fake")] <- 0
fake_satire$type[which(fake_satire$type %in% "satire")] <- 1
fake_satire$type <- as.factor(fake_satire$type)
table(fake_satire$type)
```


```{r 1Vs1_hate_junksci}
table(df_data$type)
hate_junksci <- df_data[which(df_data$type %in% c("hate", "junksci")),]
hate_junksci$type <- as.character(hate_junksci$type)
table(hate_junksci$type)
hate_junksci$type[which(hate_junksci$type %in% "hate")] <- 0
hate_junksci$type[which(hate_junksci$type %in% "junksci")] <- 1
hate_junksci$type <- as.factor(hate_junksci$type)
table(hate_junksci$type)
```

```{r 1Vs1_hate_satire}
table(df_data$type)
hate_satire <- df_data[which(df_data$type %in% c("hate", "satire")),]
hate_satire$type <- as.character(hate_satire$type)
table(hate_satire$type)
hate_satire$type[which(hate_satire$type %in% "hate")] <- 0
hate_satire$type[which(hate_satire$type %in% "satire")] <- 1
hate_satire$type <- as.factor(hate_satire$type)
table(hate_satire$type)
```

```{r 1Vs1_junksci_satire}
table(df_data$type)
junksci_satire <- df_data[which(df_data$type %in% c("junksci", "satire")),]
junksci_satire$type <- as.character(junksci_satire$type)
table(junksci_satire$type)
junksci_satire$type[which(junksci_satire$type %in% "junksci")] <- 0
junksci_satire$type[which(junksci_satire$type %in% "satire")] <- 1
junksci_satire$type <- as.factor(junksci_satire$type)
table(junksci_satire$type)
```

```{r Yuru_style}
library(e1071) # for NB and SVM
library(rpart) # for decision tree
library(ada) # for adaboost
library(class)
library(MASS) # for the example dataset 
library(plyr) # for recoding data
library(ROCR)
library(modeest) #for finding mode

do.classification <- function(train.set, test.set, cl.name) {
  ## note: to plot ROC later, we want the raw probabilities,
  ## not binary decisions
  switch(cl.name, 
         knn1 = { # here we test k=1; you should evaluate different k's
           prob = knn(train.set[,-1], test.set[,-1], cl=train.set[,1], k = 1, prob=T)
           attr(prob,"prob")[prob==0] = 1-attr(prob,"prob")[prob==0] #modified
           prob = attr(prob,"prob")
           prob
         },
         knn3 = { # here we test k=3; you should evaluate different k's
           prob = knn(train.set[,-1], test.set[,-1], cl=train.set[,1], k = 3, prob=T)
           attr(prob,"prob")[prob==0] = 1-attr(prob,"prob")[prob==0] #modified
           prob = attr(prob,"prob")
           prob
         },
         knn5 = { # here we test k=5; you should evaluate different k's
           prob = knn(train.set[,-1], test.set[,-1], cl=train.set[,1], k = 5, prob=T)
           attr(prob,"prob")[prob==0] = 1-attr(prob,"prob")[prob==0] #modified
           prob = attr(prob,"prob")
           prob
         },
         lr = { # logistic regression
           model = glm(y~., family=binomial, data=train.set)
          
           prob = predict(model, newdata=test.set, type="response") 
           prob
         },
         nb = {
           model = naiveBayes(y~., data=train.set)
           prob = predict(model, newdata=test.set, type="raw") 
           prob = prob[,2]/rowSums(prob) # renormalize the prob.
           prob
         },
         dtree = {
           model = rpart(y~., data=train.set)
                     
          prob = predict(model, newdata=test.set)
           
           if (0) { # here we use the default tree, 
             ## you should evaluate different size of tree
             ## prune the tree 
             pfit<- prune(model, cp=model$cptable[which.min(model$cptable[,"xerror"]),"CP"])
             prob = predict(pfit, newdata=test.set)
             ## plot the pruned tree 
             #plot(pfit, uniform=TRUE,main="Pruned Classification Tree")
             #text(pfit, use.n=TRUE, all=TRUE, cex=.8)             
           }
           prob = prob[,2]/rowSums(prob) # renormalize the prob.
           #prob <- prob/sum(prob)
           prob
         },
         dtreeprune = {
           model = rpart(y~., data=train.set)
                  
           prob = predict(model, newdata=test.set)
           
           if (1) { # here we prune the tree, 
             ## you should evaluate different size of tree
             ## prune the tree 
             pfit<- prune(model, cp=model$cptable[which.min(model$cptable[,"xerror"]),"CP"])
             prob = predict(pfit, newdata=test.set)
             ## plot the pruned tree 
             #plot(pfit, uniform=TRUE,main="Pruned Classification Tree")
             #text(pfit, use.n=TRUE, all=TRUE, cex=.8)             
           }
           prob = prob[,2]/rowSums(prob) # renormalize the prob.
           #prob <- prob/sum(prob)
           prob
         },
         svm = {
           model = svm(y~., data=train.set, probability=TRUE)
           if (0) { # fine-tune the model with different kernel and parameters
             ## evaluate the range of gamma parameter between 0.000001 and 0.1
             ## and cost parameter from 0.1 until 10
             tuned <- tune.svm(y~., data = train.set, 
                               kernel="radial", 
                               gamma = 10^(-6:-1), cost = 10^(-1:1))
             gamma = tuned[['best.parameters']]$gamma
             cost = tuned[['best.parameters']]$cost
             model = svm(y~., data = train.set, probability=TRUE, 
                         kernel="radial", gamma=gamma, cost=cost)                        
           }
           prob = predict(model, newdata=test.set, probability=TRUE)
           prob = attr(prob,"probabilities")
           prob = prob[,which(colnames(prob)==1)]/rowSums(prob)
           prob
         },
         svmsig = {
           model = svm(y~., data=train.set, probability=TRUE)
           if (1) { # fine-tune the model with kernel "sigmoid"
             ## evaluate the range of gamma parameter between 0.000001 and 0.1
             ## and cost parameter from 0.1 until 10
             tuned <- tune.svm(y~., data = train.set, 
                               kernel="sigmoid", 
                               gamma = 10^(-6:-1), cost = 10^(-1:1))
             gamma = tuned[['best.parameters']]$gamma
             cost = tuned[['best.parameters']]$cost
             model = svm(y~., data = train.set, probability=TRUE, 
                         kernel="radial", gamma=gamma, cost=cost)                        
           }
           prob = predict(model, newdata=test.set, probability=TRUE)
           prob = attr(prob,"probabilities")
           prob = prob[,which(colnames(prob)==1)]/rowSums(prob)
           prob
         },
         svmlin= {
           model = svm(y~., data=train.set, probability=T)
           if (1) { # fine-tune the model with kernel "linear"
             ## evaluate the range of gamma parameter between 0.000001 and 0.1
             ## and cost parameter from 0.1 until 10
             tuned <- tune.svm(y~., data = train.set, 
                               kernel="linear", 
                               gamma = 10^(-4:-1), cost = 10^(-2:1))
             #print(summary(tuned))
             gamma = tuned[['best.parameters']]$gamma
             cost = tuned[['best.parameters']]$cost
             model = svm(y~., data = train.set, probability=T, 
                         kernel="linear", gamma=gamma, cost=cost)                        
           }
           prob = predict(model, newdata=test.set, probability=T, type="raw")
           prob = attr(prob,"probabilities")
           prob = prob[,which(colnames(prob)==1)]/rowSums(prob)
           prob
         },
         ada = {
           model = ada(y~., data = train.set)
           prob = predict(model, newdata=test.set, type='probs')
           prob = prob[,2]/rowSums(prob)
           prob
         }
  ) 
}

k.fold.cv <- function(dataset, cl.name, k.fold=10, prob.cutoff=0.5, get.performance=F) {
  ## default: 10-fold CV, cut-off 0.5

  n.obs <- nrow(dataset) # no. of observations 
  s = sample(n.obs)
  errors = dim(k.fold)
  probs = NULL
  actuals = NULL
  for (k in 1:k.fold) {
    test.idx = which(s %% k.fold == (k-1) ) # use modular operator
    train.set = dataset[-test.idx,]
    test.set = dataset[test.idx,]
    prob = do.classification(train.set, test.set, cl.name)
    predicted = as.numeric(prob > prob.cutoff)
    actual = test.set$y
    confusion.matrix = table(actual,factor(predicted,levels=c(0,1)))
    confusion.matrix
    error = (confusion.matrix[1,2]+confusion.matrix[2,1]) / nrow(test.set)  
    errors[k] = error
    cat('\t\terror=',error,'\n')
    probs = c(probs,prob)
    actuals = c(actuals,actual)
    ## you may compute other measures and store them in arrays
  }
  avg.error = mean(errors)
  cat(k.fold,'-fold CV results:','avg error=',avg.error,'\n')
  
  ## plot ROC
  result = data.frame(probs,actuals)
  pred = prediction(result$probs,result$actuals)
  
  return(pred)

}

normalize <- function(x) {
return ((x - min(x)) / (max(x) - min(x))) }

model.mat.function <- function(data_combination){
model.mat<-model.matrix(data_combination$type~.,data=data_combination)[,-1]
model.mat[1:3, ]
model.mat <- as.data.frame(model.mat) #converting into data frame
model.mat$y <- data_combination$type 
return(model.mat)
}

get.predicted <- function(result,var1,var2){
  predicted.labels <- data.frame(predicted = result@labels)
  colnames(predicted.labels) <- "algo"
  predicted.labels$algo <- as.numeric(predicted.labels$algo)
  predicted.labels$algo[which(predicted.labels$algo == 1)] <- var1
  predicted.labels$algo[which(predicted.labels$algo == 2)] <- var2
  return(predicted.labels$algo)
}

do.combine <- function(df, actual.vs.predicted,var1,var2){

  model.mat <- model.mat.function(df)
  result_lr <- k.fold.cv(model.mat,'lr', get.performance = T)
  actual.vs.predicted <- cbind(actual.vs.predicted, get.predicted(result_lr,var1,var2))
  colnames(actual.vs.predicted) <- c("actual", "lr")

  result_knn1 <- k.fold.cv(model.mat,'knn1')
  actual.vs.predicted <- cbind(actual.vs.predicted, get.predicted(result_knn1,var1,var2))
  colnames(actual.vs.predicted) <- c("actual", "lr", "knn1")

  result_knn3 <- k.fold.cv(model.mat,'knn3')
  actual.vs.predicted <- cbind(actual.vs.predicted, get.predicted(result_knn3,var1,var2))
  colnames(actual.vs.predicted) <- c("actual", "lr", "knn1", 'knn3')

  #result_knn5 <- k.fold.cv(model.mat,'knn5')
  #actual.vs.predicted <- cbind(actual.vs.predicted, get.predicted(result_knn5,var1,var2))
  #colnames(actual.vs.predicted) <- c("actual", "lr", "knn1", 'knn3', 'knn5')

  result_nb <- k.fold.cv(model.mat,'nb')
  actual.vs.predicted <- cbind(actual.vs.predicted, get.predicted(result_nb,var1,var2))
  colnames(actual.vs.predicted) <- c("actual", "lr", "knn1", 'knn3', 'nb')

  result_dtree <- k.fold.cv(model.mat,'dtree')
  actual.vs.predicted <- cbind(actual.vs.predicted, get.predicted(result_dtree,var1,var2))
  colnames(actual.vs.predicted) <- c("actual", "lr", "knn1", 'knn3', 'nb', 'dtree')

  result_dtreeprune <- k.fold.cv(model.mat,'dtreeprune')
  actual.vs.predicted <- cbind(actual.vs.predicted, get.predicted(result_dtreeprune,var1,var2))
  colnames(actual.vs.predicted) <- c("actual", "lr", "knn1", 'knn3', 'nb', 'dtree', 'dtreeprune')

  result_svm <- k.fold.cv(model.mat,'svm')
  actual.vs.predicted <- cbind(actual.vs.predicted, get.predicted(result_svm,var1,var2))
  colnames(actual.vs.predicted) <- c("actual", "lr", "knn1", 'knn3', 'nb', 'dtree', 'dtreeprune', 'svm')
  
  actual.vs.predicted <- as.data.frame(actual.vs.predicted)
  
  final.prediction <- apply(actual.vs.predicted[,2:length(actual.vs.predicted)],1,mfv)
  final.prediction <- as.data.frame(final.prediction)
  actual.vs.predicted <- cbind(actual.vs.predicted, final.prediction)
  
  for(i in 1:length(actual.vs.predicted))
    actual.vs.predicted[,i] <- as.factor(actual.vs.predicted[,i])
  
 return(actual.vs.predicted)
}

```


```{r algo_bait_satire}
actual.vs.predicted.bait_satire = data.frame(actual = bait_satire$type)
final.bait_satire <- data.frame(x = bait_satire$X)
final.bait_satire <- cbind(final.bait_satire, do.combine(bait_satire[,-1], actual.vs.predicted.bait_satire, "bait", "satire"))

final.bait_satire$actual <- as.character(final.bait_satire$actual)
final.bait_satire$actual[which(final.bait_satire$actual %in% '0')] <- "bait"
final.bait_satire$actual[which(final.bait_satire$actual %in% '1')] <- "satire"
final.bait_satire$actual <- as.factor(final.bait_satire$actual)
```

```{r algo_bait_bias}
actual.vs.predicted.bait_bias= data.frame(actual = bait_bias$type)
final.bait_bias <- data.frame(x = bait_bias$X)
final.bait_bias <- cbind(final.bait_bias, do.combine(bait_bias[,-1], actual.vs.predicted.bait_bias, "bait", "bias"))
final.bait_bias$actual <- as.character(final.bait_bias$actual)
final.bait_bias$actual[which(final.bait_bias$actual %in% '0')] <- "bait"
final.bait_bias$actual[which(final.bait_bias$actual %in% '1')] <- "bias"
final.bait_bias$actual <- as.factor(final.bait_bias$actual)
```

```{r algo_bait_bs}
actual.vs.predicted.bait_bs = data.frame(actual = bait_bs$type)
final.bait_bs <- data.frame(x = bait_bs$X)
final.bait_bs <- cbind(final.bait_bs,do.combine(bait_bs[,-1], actual.vs.predicted.bait_bs,"bait","bs"))
final.bait_bs$actual <- as.character(final.bait_bs$actual)
final.bait_bs$actual[which(final.bait_bs$actual %in% '0')] <- "bait"
final.bait_bs$actual[which(final.bait_bs$actual %in% '1')] <- "bs"
final.bait_bs$actual <- as.factor(final.bait_bs$actual)
```

```{r algo_bait_conspiracy}
actual.vs.predicted.bait_conspiracy = data.frame(actual = bait_conspiracy$type)
final.bait_conspiracy <- data.frame(x = bait_conspiracy$X)
final.bait_conspiracy <- cbind(final.bait_conspiracy,do.combine(bait_conspiracy[,-1],actual.vs.predicted.bait_conspiracy,"bait","conspiracy"))
final.bait_conspiracy$actual <- as.character(final.bait_conspiracy$actual)
final.bait_conspiracy$actual[which(final.bait_conspiracy$actual %in% '0')] <- "bait"
final.bait_conspiracy$actual[which(final.bait_conspiracy$actual %in% '1')] <- "conspiracy"
final.bait_conspiracy$actual <- as.factor(final.bait_conspiracy$actual)
```

```{r algo_bait_fake}
actual.vs.predicted.bait_fake = data.frame(actual = bait_fake$type)
final.bait_fake <- data.frame(x = bait_fake$X)
final.bait_fake <- cbind(final.bait_fake,do.combine(bait_fake[,-1], actual.vs.predicted.bait_fake,"bait","fake"))
final.bait_fake$actual <- as.character(final.bait_fake$actual)
final.bait_fake$actual[which(final.bait_fake$actual %in% '0')] <- "bait"
final.bait_fake$actual[which(final.bait_fake$actual %in% '1')] <- "fake"
final.bait_fake$actual <- as.factor(final.bait_fake$actual)
```

```{r algo_bait_hate}
actual.vs.predicted.bait_hate = data.frame(actual = bait_hate$type)
final.bait_hate <- data.frame(x = bait_hate$X)
final.bait_hate<- cbind(final.bait_hate,do.combine(bait_hate[,-1], actual.vs.predicted.bait_hate,"bait","hate"))
final.bait_hate$actual <- as.character(final.bait_hate$actual)
final.bait_hate$actual[which(final.bait_hate$actual %in% '0')] <- "bait"
final.bait_hate$actual[which(final.bait_hate$actual %in% '1')] <- "hate"
final.bait_hate$actual <- as.factor(final.bait_hate$actual)
```

```{r algo_bait_junkSci}
actual.vs.predicted.bait_junkSci = data.frame(actual = bait_junkSci$type)
final.bait_junkSci <- data.frame(x = bait_junkSci$X)
final.bait_junkSci <- cbind(final.bait_junkSci,do.combine(bait_junkSci[,-1], actual.vs.predicted.bait_junkSci,"bait","junksci"))
final.bait_junkSci$actual <- as.character(final.bait_junkSci$actual)
final.bait_junkSci$actual[which(final.bait_junkSci$actual %in% '0')] <- "bait"
final.bait_junkSci$actual[which(final.bait_junkSci$actual %in% '1')] <- "junksci"
final.bait_junkSci$actual <- as.factor(final.bait_junkSci$actual)
```

```{r algo_bias_bs}
actual.vs.predicted.bias_bs = data.frame(actual = bias_bs$type)
final.bias_bs <- data.frame(x = bias_bs$X)
final.bias_bs <- cbind(final.bias_bs,do.combine(bias_bs[,-1], actual.vs.predicted.bias_bs,"bias","bs"))
final.bias_bs$actual <- as.character(final.bias_bs$actual)
final.bias_bs$actual[which(final.bias_bs$actual %in% '0')] <- "bias"
final.bias_bs$actual[which(final.bias_bs$actual %in% '1')] <- "bs"
final.bias_bs$actual <- as.factor(final.bias_bs$actual)
```

```{r algo_bias_conspiracy}
actual.vs.predicted.bias_conspiracy = data.frame(actual = bias_conspiracy$type)
final.bias_conspiracy <- data.frame(x = bias_conspiracy$X)
final.bias_conspiracy <- cbind(final.bias_conspiracy,do.combine(bias_conspiracy[,-1],actual.vs.predicted.bias_conspiracy,"bias","conspiracy"))
final.bias_conspiracy$actual <- as.character(final.bias_conspiracy$actual)
final.bias_conspiracy$actual[which(final.bias_conspiracy$actual %in% '0')] <- "bias"
final.bias_conspiracy$actual[which(final.bias_conspiracy$actual %in% '1')] <- "conspiracy"
final.bias_conspiracy$actual <- as.factor(final.bias_conspiracy$actual)
```

```{r algo_bias_fake}
actual.vs.predicted.bias_fake = data.frame(actual = bias_fake$type)
final.bias_fake <- data.frame(x = bias_fake$X)
final.bias_fake <- cbind(final.bias_fake,do.combine(bias_fake[,-1], actual.vs.predicted.bias_fake,"bias","fake"))
final.bias_fake$actual <- as.character(final.bias_fake$actual)
final.bias_fake$actual[which(final.bias_fake$actual %in% '0')] <- "bias"
final.bias_fake$actual[which(final.bias_fake$actual %in% '1')] <- "fake"
final.bias_fake$actual <- as.factor(final.bias_fake$actual)
```

```{r algo_bias_hate}
actual.vs.predicted.bias_hate = data.frame(actual = bias_hate$type)
final.bias_hate <- data.frame(x = bias_hate$X)
final.bias_hate <- cbind(final.bias_hate,do.combine(bias_hate[,-1], actual.vs.predicted.bias_hate,"bias","hate"))
final.bias_hate$actual <- as.character(final.bias_hate$actual)
final.bias_hate$actual[which(final.bias_hate$actual %in% '0')] <- "bias"
final.bias_hate$actual[which(final.bias_hate$actual %in% '1')] <- "hate"
final.bias_hate$actual <- as.factor(final.bias_hate$actual)
```

```{r algo_bias_junksci}
actual.vs.predicted.bias_junksci = data.frame(actual = bias_junksci$type)
final.bias_junksci <- data.frame(x = bias_junksci$X)
final.bias_junksci <- cbind(final.bias_junksci,do.combine(bias_junksci[,-1], actual.vs.predicted.bias_junksci,"bias","junksci"))
final.bias_junksci$actual <- as.character(final.bias_junksci$actual)
final.bias_junksci$actual[which(final.bias_junksci$actual %in% '0')] <- "bias"
final.bias_junksci$actual[which(final.bias_junksci$actual %in% '1')] <- "junksci"
final.bias_junksci$actual <- as.factor(final.bias_junksci$actual)
```

```{r algo_bias_satire}
actual.vs.predicted.bias_satire = data.frame(actual = bias_satire$type)
final.bias_satire <- data.frame(x = bias_satire$X)
final.bias_satire <- cbind(final.bias_satire,do.combine(bias_satire[,-1], actual.vs.predicted.bias_satire,"bias","satire"))
final.bias_satire$actual <- as.character(final.bias_satire$actual)
final.bias_satire$actual[which(final.bias_satire$actual %in% '0')] <- "bias"
final.bias_satire$actual[which(final.bias_satire$actual %in% '1')] <- "satire"
final.bias_satire$actual <- as.factor(final.bias_satire$actual)
```

```{r algo_bs_conspiracy}
actual.vs.predicted.bs_conspiracy = data.frame(actual = bs_conspiracy$type)
final.bs_conspiracy <- data.frame(x = bs_conspiracy$X)
final.bs_conspiracy <- cbidn(final.bs_conspiracy,do.combine(bs_conspiracy[,-1], actual.vs.predicted.bs_conspiracy,"bs","conspiracy"))
final.bs_conspiracy$actual <- as.character(final.bs_conspiracy$actual)
final.bs_conspiracy$actual[which(final.bs_conspiracy$actual %in% '0')] <- "bs"
final.bs_conspiracy$actual[which(final.bs_conspiracy$actual %in% '1')] <- "conspiracy"
final.bs_conspiracy$actual <- as.factor(final.bs_conspiracy$actual)
```

```{r algo_bs_fake}
actual.vs.predicted.bs_fake = data.frame(actual = bs_fake$type)
final.bs_fake <- data.frame(x = bs_fake$X)
final.bs_fake <- cbind(final.bs_fake,do.combine(bs_fake[,-1], actual.vs.predicted.bs_fake,"bs","fake"))
final.bs_fake$actual <- as.character(final.bs_fake$actual)
final.bs_fake$actual[which(final.bs_fake$actual %in% '0')] <- "bs"
final.bs_fake$actual[which(final.bs_fake$actual %in% '1')] <- "fake"
final.bs_fake$actual <- as.factor(final.bs_fake$actual)
```

```{r algo_bs_hate}
actual.vs.predicted.bs_hate = data.frame(actual = bs_hate$type)
final.bs_hate <- data.frame(x = bs_hate$X)
final.bs_hate <- cbind(final.bs_hate,do.combine(bs_hate[,-1], actual.vs.predicted.bs_hate,"bs","hate"))
final.bs_hate$actual <- as.character(final.bs_hate$actual)
final.bs_hate$actual[which(final.bs_hate$actual %in% '0')] <- "bs"
final.bs_hate$actual[which(final.bs_hate$actual %in% '1')] <- "hate"
final.bs_hate$actual <- as.factor(final.bs_hate$actual)
```

```{r algo_bs_junksci}
actual.vs.predicted.bs_junksci = data.frame(actual = bs_junksci$type)
final.bs_junksci <- data.frame(x = bs_junksci$X)
final.bs_junksci <- cbind(final.bs_junksci,do.combine(bs_junksci[,-1], actual.vs.predicted.bs_junksci,"bs","junksci"))
final.bs_junksci$actual <- as.character(final.bs_junksci$actual)
final.bs_junksci$actual[which(final.bs_junksci$actual %in% '0')] <- "bs"
final.bs_junksci$actual[which(final.bs_junksci$actual %in% '1')] <- "junksci"
final.bs_junksci$actual <- as.factor(final.bs_junksci$actual)
```

```{r algo_bs_satire}
actual.vs.predicted.bs_satire = data.frame(actual = bs_satire$type)
final.bs_satire <- data.frame(x = bs_satire$X)
final.bs_satire <- cbind(final.bs_satire,do.combine(bs_satire[,-1], actual.vs.predicted.bs_satire,"bs","satire"))
final.bs_satire$actual <- as.character(final.bs_satire$actual)
final.bs_satire$actual[which(final.bs_satire$actual %in% '0')] <- "bs"
final.bs_satire$actual[which(final.bs_satire$actual %in% '1')] <- "satire"
final.bs_satire$actual <- as.factor(final.bs_satire$actual)
```

```{r algo_conspiracy_fake}
actual.vs.predicted.conspiracy_fake= data.frame(actual = conspiracy_fake$type)
final.conspiracy_fake <- data.frame(x = conspiracy_fake$X)
final.conspiracy_fake <- cbind(final.conspiracy_fake,do.combine(conspiracy_fake[,-1], actual.vs.predicted.conspiracy_fake,"conspiracy","fake"))
final.conspiracy_fake$actual <- as.character(final.conspiracy_fake$actual)
final.conspiracy_fake$actual[which(final.conspiracy_fake$actual %in% '0')] <- "conspiracy"
final.conspiracy_fake$actual[which(final.conspiracy_fake$actual %in% '1')] <- "fake"
final.conspiracy_fake$actual <- as.factor(final.conspiracy_fake$actual)
```

```{r algo_conspiracy_hate}
actual.vs.predicted.conspiracy_hate = data.frame(actual =conspiracy_hate$type)
final.conspiracy_hate <- data.frame(x = conspiracy_hate$X)
final.conspiracy_hate <- cbind(final.conspiracy_hate,do.combine(conspiracy_hate[,-1], actual.vs.predicted.conspiracy_hate,"conspiracy","hate"))
final.conspiracy_hate$actual <- as.character(final.conspiracy_hate$actual)
final.conspiracy_hate$actual[which(final.conspiracy_hate$actual %in% '0')] <- "conspiracy"
final.conspiracy_hate$actual[which(final.conspiracy_hate$actual %in% '1')] <- "hate"
final.conspiracy_hate$actual <- as.factor(final.conspiracy_hate$actual)
```

```{r algo_conspiracy_junksci}
actual.vs.predicted.conspiracy_junksci = data.frame(actual = conspiracy_junksci$type)
final.conspiracy_junksci <- data.frame(x = conspiracy_junksci$X)
final.conspiracy_junksci <- cbind(final.conspiracy_junksci,do.combine(conspiracy_junksci[,-1], actual.vs.predicted.conspiracy_junksci,"conspiracy","junksci"))
final.conspiracy_junksci$actual <- as.character(final.conspiracy_junksci$actual)
final.conspiracy_junksci$actual[which(final.conspiracy_junksci$actual %in% '0')] <- "conspiracy"
final.conspiracy_junksci$actual[which(final.conspiracy_junksci$actual %in% '1')] <- "junksci"
final.conspiracy_junksci$actual <- as.factor(final.conspiracy_junksci$actual)
```

```{r algo_conspiracy_satire}
actual.vs.predicted.conspiracy_satire = data.frame(actual = conspiracy_satire$type)
final.conspiracy_satire <- data.frame(x = conspiracy_satire$X)
final.conspiracy_satire <- cbind(final.conspiracy_satire,do.combine(conspiracy_satire[,-1], actual.vs.predicted.conspiracy_satire, actual.vs.predicted.conspiracy_hate,"conspiracy","satire"))
final.conspiracy_satire$actual <- as.character(final.conspiracy_satire$actual)
final.conspiracy_satire$actual[which(final.conspiracy_satire$actual %in% '0')] <- "conspiracy"
final.conspiracy_satire$actual[which(final.conspiracy_satire$actual %in% '1')] <- "satire"
final.conspiracy_satire$actual <- as.factor(final.conspiracy_satire$actual)
```

```{r algo_fake_hate}
actual.vs.predicted.fake_hate = data.frame(actual = fake_hate$type)
final.fake_hate <- data.frame(x = fake_hate$X)
final.fake_hate <- cbind(final.fake_hate,do.combine(fake_hate[,-1], actual.vs.predicted.fake_hate,"fake","hate"))
final.fake_hate$actual <- as.character(final.fake_hate$actual)
final.fake_hate$actual[which(final.fake_hate$actual %in% '0')] <- "fake"
final.fake_hate$actual[which(final.fake_hate$actual %in% '1')] <- "hate"
final.fake_hate$actual <- as.factor(final.fake_hate$actual)
```

```{r algo_fake_junksci}
actual.vs.predicted.fake_junksci = data.frame(actual = fake_junksci$type)
final.fake_junksci <- data.frame(x = fake_junksci$X)
final.fake_junksci <- cbind(final.fake_junksci,do.combine(fake_junksci[,-1], actual.vs.predicted.fake_junksci,"fake","junksci"))
final.fake_junksci$actual <- as.character(final.fake_junksci$actual)
final.fake_junksci$actual[which(final.fake_junksci$actual %in% '0')] <- "fake"
final.fake_junksci$actual[which(final.fake_junksci$actual %in% '1')] <- "junksci"
final.fake_junksci$actual <- as.factor(final.fake_junksci$actual)
```

```{r algo_fake_satire}
actual.vs.predicted.fake_satire = data.frame(actual = fake_satire$type)
final.fake_satire <- data.frame(x = fake_satire$X)
final.fake_satire <- cbind(final.fake_satire,do.combine(fake_satire[,-1], actual.vs.predicted.fake_satire,"fake","satire"))
final.fake_satire$actual <- as.character(final.fake_satire$actual)
final.fake_satire$actual[which(final.fake_satire$actual %in% '0')] <- "fake"
final.fake_satire$actual[which(final.fake_satire$actual %in% '1')] <- "satire"
final.fake_satire$actual <- as.factor(final.fake_satire$actual)
```

```{r algo_hate_junksci}
actual.vs.predicted.hate_junksci = data.frame(actual = hate_junksci$type)
final.hate_junksci <- data.frame(x = hate_junksci$X)
final.hate_junksci <- cbind(final.hate_junksci,do.combine(hate_junksci[,-1], actual.vs.predicted.hate_junksci,"hate","junksci"))
final.hate_junksci$actual <- as.character(final.hate_junksci$actual)
final.hate_junksci$actual[which(final.hate_junksci$actual %in% '0')] <- "hate"
final.hate_junksci$actual[which(final.hate_junksci$actual %in% '1')] <- "junksci"
final.hate_junksci$actual <- as.factor(final.hate_junksci$actual)
```

```{r algo_hate_satire}
actual.vs.predicted.hate_satire = data.frame(actual = hate_satire$type)
final.hate_satire <- data.frame(x = hate_satire$X)
final.hate_satire<- cbind(final.hate_satire,do.combine(hate_satire[,-1], actual.vs.predicted.hate_satire,"hate","satire"))
final.hate_satire$actual <- as.character(final.hate_satire$actual)
final.hate_satire$actual[which(final.hate_satire$actual %in% '0')] <- "hate"
final.hate_satire$actual[which(final.hate_satire$actual %in% '1')] <- "satire"
final.hate_satire$actual <- as.factor(final.hate_satire$actual)
```

```{r algo_junksci_satire}
actual.vs.predicted.junksci_satire = data.frame(actual = junksci_satire$type)
final.junksci_satire <- data.frame(x = junksci_satire$X)
final.junksci_satire<- cbind(final.junksci_satire,do.combine(junksci_satire[,-1], actual.vs.predicted.junksci_satire,"junksci","satire"))
final.junksci_satire$actual <- as.character(final.junksci_satire$actual)
final.junksci_satire$actual[which(final.junksci_satire$actual %in% '0')] <- "junksci"
final.junksci_satire$actual[which(final.junksci_satire$actual %in% '1')] <- "satire"
final.junksci_satire$actual <- as.factor(final.junksci_satire$actual)
```

```{r }
##################################################################
############ Taking too much time to execute #####################
##################################################################

#result_svmsig <- k.fold.cv(model.mat.bait_satire,'svmsig')
#actual.vs.predicted.bait_satire <- cbind(actual.vs.predicted.bait_satire, get.predicted(result_svmsig))
#colnames(actual.vs.predicted.bait_satire) <- c("actual", "lr", "knn1", 'knn3', 'knn5', 'nb', 'dtree', #'dtreeprune', 'svm', 'svmsig')

#result_svmlin <- k.fold.cv(model.mat.bait_satire,'svmlin')
#actual.vs.predicted.bait_satire <- cbind(actual.vs.predicted.bait_satire, get.predicted(result_svmlin))
#colnames(actual.vs.predicted.bait_satire) <- c("actual", "lr", "knn1", 'knn3', 'knn5', 'nb', 'dtree', #'dtreeprune', 'svm', 'svmsig', 'svmlin')

#result_ada <- k.fold.cv(model.mat.bait_satire,'ada')
#actual.vs.predicted.bait_satire <- cbind(actual.vs.predicted.bait_satire, get.predicted(result_ada))
#colnames(actual.vs.predicted.bait_satire) <- c("actual", "lr", "knn1", 'knn3', 'knn5', 'nb', 'dtree', #'dtreeprune', 'svm', 'svmsig', 'svmlin', 'ada')

##################################################################
############ Taking too much time to execute #####################
##################################################################

```

```{r Evaluation_Implementation}
evaluation_function <- function (result_table){
        library(pROC)
#Type 1 Implementation  
        confusion.matrix1 <- table(result_table$actual,result_table$final.prediction)
        names(attributes(confusion.matrix1)$dimnames) <- c("Actual","Predicted")
        error1     <- (confusion.matrix1[2,1]+confusion.matrix1[1,2])/nrow(result_table)
        accuracy1  <- (confusion.matrix1[1,1]+confusion.matrix1[2,2])/nrow(result_table)
        precision1 <- (confusion.matrix1[1,1]) / (confusion.matrix1[1,1]+confusion.matrix1[2,1])
        recall1    <- (confusion.matrix1[1,1]) / (confusion.matrix1[1,1]+confusion.matrix1[1,2]) 
        fscore1    <- (2* precision1*recall1)/ (precision1+recall1)
        result_table$actual <-as.numeric(result_table$actual)
        ROC1 <- roc(result_table$final.prediction, result_table$actual)
        AUC1 <- auc(ROC1)
        type1_output <- data.frame(Accuracy = accuracy1,Error = error1, Precision = precision1, Recall =     recall1,F_Score = fscore1, AUC = AUC1 )
        ############# return (type1_output)
        
#Type 2 Implementation  
        type2_output = dim(1)
        final_type2 = dim(1)
        no_cols <- ncol(result_table)-1  #removing the last column, which is "final prediction"
        
        for( i in no_cols:2)
            {
                confusion.matrix2 <- table(result_table$actual, result_table[,i])
                names(attributes(confusion.matrix2)$dimnames) <- c("Actual","Predicted")
                error2     <- (confusion.matrix2[2,1]+confusion.matrix2[1,2])/nrow(result_table)
                accuracy2 <- (confusion.matrix2[1,1]+confusion.matrix2[2,2])/nrow(result_table)
                precision2 <- (confusion.matrix2[1,1]) / (confusion.matrix2[1,1]+confusion.matrix2[2,1])
                recall2    <- (confusion.matrix2[1,1]) / (confusion.matrix2[1,1]+confusion.matrix2[1,2]) 
                fscore2    <- (2* precision2*recall2)/ (precision2+recall2)
                result_table$actual <-as.numeric(result_table$actual)
                ROC2 <- roc(result_table$final.prediction, result_table$actual)
                AUC2 <- auc(ROC2)
                type2_output <- data.frame(Accuracy = accuracy2,Error = error2, Precision = precision2, Recall = recall2,F_Score = fscore2, AUC = AUC2)
                final_type2<-rbind(final_type2,type2_output)
            }

        mean <- as.data.frame(mean(dim(1)))
        #To find average of the Values
        for( i in 1:ncol(final_type2) )
            {
               mean[,i] <- mean(final_type2[,i])
            }

        colnames(mean) <- c("Accuracy","Error","Precision","Recall","F_Score","AUC")
        ##########return(mean)
        
#Type 3 Implementation        
        type3_output = dim(1)

        confusion.matrix3_7 <- table(result_table$actual, result_table[,8])
        names(attributes(confusion.matrix2)$dimnames) <- c("Actual","Predicted")
  
        confusion.matrix3_6 <- table(result_table$actual, result_table[,7])
        names(attributes(confusion.matrix2)$dimnames) <- c("Actual","Predicted")
      
        confusion.matrix3_5 <- table(result_table$actual, result_table[,6])
        names(attributes(confusion.matrix2)$dimnames) <- c("Actual","Predicted")
      
        confusion.matrix3_4 <- table(result_table$actual, result_table[,5])
        names(attributes(confusion.matrix2)$dimnames) <- c("Actual","Predicted")
      
        confusion.matrix3_3 <- table(result_table$actual, result_table[,4])
        names(attributes(confusion.matrix2)$dimnames) <- c("Actual","Predicted")
      
        confusion.matrix3_2 <- table(result_table$actual, result_table[,3])
        names(attributes(confusion.matrix2)$dimnames) <- c("Actual","Predicted")
      
        confusion.matrix3_1 <- table(result_table$actual, result_table[,2])
        names(attributes(confusion.matrix2)$dimnames) <- c("Actual","Predicted")
  
        true_pos <- mean(confusion.matrix3_1[1,1],confusion.matrix3_2[1,1],confusion.matrix3_3[1,1],confusion.matrix3_4[1,1],confusion.matrix3_5[1,1],confusion.matrix3_6[1,1],confusion.matrix3_7[1,1])
      
        false_neg <- mean(confusion.matrix3_1[1,2],confusion.matrix3_2[1,2],confusion.matrix3_3[1,2],confusion.matrix3_4[1,2],confusion.matrix3_5[1,2],confusion.matrix3_6[1,2],confusion.matrix3_7[1,2])
      
        false_pos <- mean(confusion.matrix3_1[2,1],confusion.matrix3_2[2,1],confusion.matrix3_3[2,1],confusion.matrix3_4[2,1],confusion.matrix3_5[2,1],confusion.matrix3_6[2,1],confusion.matrix3_7[2,1])
      
        true_neg <- mean(confusion.matrix3_1[2,2],confusion.matrix3_2[2,2],confusion.matrix3_3[2,2],confusion.matrix3_4[2,2],confusion.matrix3_5[2,2],confusion.matrix3_6[2,2],confusion.matrix3_7[2,2])
  
        c1 <- c(true_pos,false_neg)
        c2 <- c(false_pos,true_neg)
        confusion.matrix3 <- rbind(c1,c2)
  
        error3 <- (confusion.matrix3[2,1]+confusion.matrix3[1,2])/nrow(result_table)
        accuracy3 <- (confusion.matrix3[1,1]+confusion.matrix3[2,2])/nrow(result_table)
        precision3 <- (confusion.matrix3[1,1])/(confusion.matrix3[1,1]+confusion.matrix3[2,1])
        recall3 <- (confusion.matrix3[1,1])/(confusion.matrix3[1,1]+confusion.matrix3[1,2])
        fscore3 <- (2* precision3*recall3)/ (precision3+recall3)
        result_table$actual <-as.numeric(result_table$actual)
        ROC3 <- roc(result_table$final.prediction, result_table$actual)
        AUC3 <- auc(ROC3)
        type3_output <- data.frame(Accuracy = accuracy3,Error = error3,Precision = precision3, Recall = recall3,F_Score = fscore3, AUC = AUC3) 
        #########return(type3_output)
        
        final_eval_table <- rbind(type1_output,mean,type3_output)
        eval_names<-as.data.frame(c("General","Macro","Micro"))
        colnames(eval_names)<- c("Evaluation Method")
        final_eval_table <- cbind(eval_names,final_eval_table)
        return(final_eval_table)
}
```